theme: jekyll-theme-primer
title: [3D models at CU]
description: [licensed CC0]
highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

    scope:
      path: "attached"
    values:
      permalink: /:name

    scope:
      path: "_posts"
    values:
      permalink: /:title
